### ISSUE TITLE
nuxt 3 support?

### ISSUE THREAD

**Issue by MattCCC** [daliborgogic/nuxt-interpolation#25]
Hi, thank you for the plugin. It does not seem to work with Nuxt 3. I receive following error:

```
 ERROR  'default' is not exported by node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by virtual:/Users/a/demo-app/.nuxt/interpolation.js
file: virtual:/Users/a/demo-app/.nuxt/interpolation.js:1:0
1: import Vue from 'vue'
   ^
2: 
3: export default ({ app: { router } }) => {


 ERROR  'default' is not exported by node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by virtual:/Users/a/demo-app/.nuxt/interpolation.js

  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12521:16)
  at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:12879:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:11509:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6477:38)
  at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6477:38)
  at MemberExpression.bind (node_modules/rollup/dist/shared/rollup.js:8706:49)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:5342:23)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:8950:15)
  at ExpressionStatement.bind (node_modules/rollup/dist/shared/rollup.js:5342:23)

```

Any idea how we could workaround it?

**Comment by daliborgogic** [comment]
Hi @MattCCC. Correct, it's nuxt v2 only. Short with time but have separated version for v3 https://github.com/daliborgogic/interpolation. Feel free to use.

**Comment by mrleblanc101** [comment]
@daliborgogic Maybe linking to it in the README would be a good idea for people migrating ?
Or dev that support legacy Nuxt 2 codebase and new Nuxt 3 codebase, like me 😅

**Comment by daliborgogic** [comment]
@mrleblanc101 feel free to make a PR 🙌
